services:
  - type: web
    name: SimulacaoAposentadoria
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: Bololo@10
      - key: DB_NAME
        value: aposentadoriadb
      - key: DB_PORT
        value: "3306"  # Valor da porta como string
