services:
  - type: web
    name: SimulacaoAposentadoria
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"  # Altere "main" para o nome correto do seu arquivo
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DB_HOST
        value: <HOST_DO_BANCO_NO_RENDER>
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: Bololo@10
      - key: DB_NAME
        value: aposentadoriadb
      - key: DB_PORT
        value: "3306"
